version: '3.8'

services:
  app:
    build: .
    container_name: washing-monitor-app
    restart: unless-stopped
    volumes:
      - ./server/config.json:/app/server/config.json:ro
      - ./data:/app/data
    environment:
      - TZ=Europe/Zurich
      - WEB_HOST=0.0.0.0
      - WEB_PORT=8080
      - DATABASE_PATH=/app/data/washing_machines.db
    networks:
      edge:
        aliases:
          - wms-app

networks:
  edge:
    external: true
    name: proxy