services:
  app:
    build: .
    container_name: washing-machine-status
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Europe/Zurich
      - WEB_HOST=0.0.0.0
      - WEB_PORT=8080
      - DATABASE_PATH=/app/data/washing_machines.db
    env_file:
      - ./data/.env
    networks:
      edge:
        aliases:
          - wms-app

networks:
  edge:
    external: true
    name: proxy